# Generated by Django 2.0 on 2018-02-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_once',
            field=models.BooleanField(default=True),
        ),
    ]
