# Generated by Django 2.0 on 2018-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180218_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='until',
            field=models.DateTimeField(null=True),
        ),
    ]
