# Generated by Django 2.0 on 2018-03-09 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='frequency',
            field=models.CharField(default='* * * * *', help_text='Частота в формате crontab (https://ru.wikipedia.org/wiki/Cron#crontab)', max_length=200, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='groups',
            field=models.ManyToManyField(to='groups.Group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_once',
            field=models.BooleanField(default=True, verbose_name='Отправить один раз'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='until',
            field=models.DateTimeField(null=True, verbose_name='Срок отправки'),
        ),
    ]
