# Generated by Django 2.0 on 2017-12-25 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171210_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarypassword',
            name='value',
        ),
        migrations.AddField(
            model_name='temporarypassword',
            name='password_value',
            field=models.CharField(default='LXjrDlBi', max_length=32),
        ),
        migrations.AlterField(
            model_name='temporarypassword',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 22, 52, 22, 195433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='temporarypassword',
            name='level',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'student'), (2, 'teacher')], default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'student'), (2, 'teacher')], default=0),
        ),
    ]
