# Generated by Django 2.0 on 2017-12-28 15:22

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171226_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarypassword',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporarypassword',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 15, 22, 16, 184617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='temporarypassword',
            name='password_value',
            field=models.CharField(default='genGvWwO', max_length=32),
        ),
    ]
