# Generated by Django 2.0 on 2018-01-16 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171228_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'admin'), (1, 'student'), (2, 'teacher')], default=2)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2018, 1, 23, 18, 46, 26, 975851, tzinfo=utc))),
                ('password_value', models.CharField(default='2QDpXwbn', max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TemporaryPassword',
        ),
    ]
