# Generated by Django 2.0 on 2018-01-16 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180116_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationcode',
            name='password_value',
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(default='b5vjq6WD', max_length=32),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 18, 47, 0, 111915, tzinfo=utc)),
        ),
    ]
