# Generated by Django 2.0 on 2018-01-16 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180116_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(default='m3Iv0rKp', max_length=32),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 19, 49, 56, 156245, tzinfo=utc)),
        ),
    ]
