# Generated by Django 2.0 on 2018-01-27 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180117_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(default='uVWp9rGM', max_length=32),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 15, 20, 51, 826320, tzinfo=utc)),
        ),
    ]
