# Generated by Django 2.0 on 2018-02-12 21:07

from django.db import migrations, models
import school_1329_server.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180127_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(default=school_1329_server.users.utils.generate_registration_code, max_length=32),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expiration_date',
            field=models.DateTimeField(default=school_1329_server.users.utils.generate_expiration_date),
        ),
    ]
