# Generated by Django 2.0 on 2018-03-09 17:55

from django.db import migrations, models
import school_1329_server.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_fcm_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationcode',
            options={'verbose_name': 'Код регистрации', 'verbose_name_plural': 'Коды регистрации'},
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(default=school_1329_server.users.utils.generate_registration_code, max_length=32, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expiration_date',
            field=models.DateTimeField(default=school_1329_server.users.utils.generate_expiration_date, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='level',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Ученик'), (2, 'Учитель')], default=2, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Ученик'), (2, 'Учитель')], default=0, verbose_name='Уровень'),
        ),
    ]
