# Generated by Django 2.0 on 2018-02-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='ScheduleSubject',
        ),
    ]
