# Generated by Django 2.0 on 2018-02-03 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_scheduleitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleItem',
            new_name='ScheduleLesson',
        ),
    ]
