# Generated by Django 2.0 on 2018-02-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20180212_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelesson',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
