# Generated by Django 2.0 on 2018-03-09 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_schedulelesson_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulelesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='schedulesubject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='groups',
            field=models.ManyToManyField(blank=True, to='groups.Group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='place',
            field=models.CharField(max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='start_time',
            field=models.TimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.ScheduleSubject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='schedulesubject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
