# Generated by Django 2.0 on 2018-03-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20180310_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ScheduleSubject', verbose_name='Предмет'),
        ),
    ]
